### ISSUE TITLE
还不如用原版啊

### ISSUE THREAD

**Issue by yiqiejieliu** [sunweiliang/BaiDuYunCrack#3]
![img_0377](https://user-images.githubusercontent.com/15229967/43639241-182630e4-974e-11e8-85ff-0888b3de2bab.jpg)
![img_0378](https://user-images.githubusercontent.com/15229967/43639246-1f2c085a-974e-11e8-9de4-d813bb6cd308.jpg)

**Comment by sunweiliang** [comment]
1.你爱用不用，我又不是卖给你的
2.原版限制10K，现在172K，还不知足？这玩意随机的，有的就快。

**Comment by yiqiejieliu** [comment]
上面2张图，图一是破解 58K/S 图二未破解 172K/S  我就说明下情况而已
